### ISSUE TITLE
Dashboard cannot open node detail on devnet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/tfgrid_dashboard#504]
```
{"errors":[{"message":"Cannot query field \"ip\" on type \"Twin\". Did you mean \"id\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"ip\" on type \"Twin\". Did you mean \"id\"?","    at Object.Field (/squid/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)","    at Object.enter (/squid/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/squid/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/squid/node_modules/graphql/language/visitor.js:243:26)","    at validate (/squid/node_modules/graphql/validation/validate.js:69:24)","    at validate (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)","    at processGraphQLRequest (/squid/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/squid/node_modules/apollo-server-core/dist/runHttpQuery.js:221:30)"]}}}]}

```

**Comment by zaelgohary** [comment]
@DylanVerstraete Can you demonstrate how did you see this error?

**Comment by zaelgohary** [comment]
Removed IP from GQL when querying for farm & node details.

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/221392790-b4e755e1-48aa-4df2-ad0f-7f600e297797.png)
